"""Tests for iptables.py — iptables-save and nftables parser + auditor.

Run with:  python3 tests/test_iptables.py
"""
import os
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from flintlock.iptables import (
    parse_iptables,
    check_default_policy_iptables,
    check_any_any_accept_iptables,
    check_internet_ingress_iptables,
    check_forward_chain_iptables,
    check_missing_logging_iptables,
    check_icmp_unrestricted_iptables,
    audit_iptables,
    parse_nftables,
    check_default_policy_nftables,
    check_any_any_accept_nftables,
    check_internet_ingress_nftables,
    check_missing_logging_nftables,
    check_icmp_unrestricted_nftables,
    audit_nftables,
)

# ── Test data ─────────────────────────────────────────────────────────────────

IPTABLES_SECURE = """\
# Generated by iptables-save
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p tcp -s 10.0.0.0/8 --dport 22 -j LOG --log-prefix "[SSH] "
-A INPUT -p tcp -s 10.0.0.0/8 --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 443 -j LOG --log-prefix "[HTTPS] "
-A INPUT -p tcp --dport 443 -j ACCEPT
-A INPUT -j DROP
COMMIT
"""

IPTABLES_RISKY = """\
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 3389 -j ACCEPT
-A INPUT -j ACCEPT
-A FORWARD -j ACCEPT
-A INPUT -p icmp --icmp-type echo-request -j ACCEPT
COMMIT
"""

IPTABLES_IPV6 = """\
# ip6tables
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
COMMIT
"""

NFTABLES_SECURE = """\
table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iif lo accept
        ct state established,related accept
        tcp dport 443 log prefix "[HTTPS] " accept
    }
    chain forward {
        type filter hook forward priority 0; policy drop;
    }
    chain output {
        type filter hook output priority 0; policy accept;
    }
}
"""

NFTABLES_RISKY = """\
table inet filter {
    chain input {
        type filter hook input priority 0; policy accept;
        tcp dport 22 accept
        tcp dport 3389 accept
        accept
        icmp type echo-request accept
    }
    chain forward {
        type filter hook forward priority 0; policy accept;
    }
}
"""


def _write(content: str, suffix=".txt") -> str:
    fd, path = tempfile.mkstemp(suffix=suffix)
    with os.fdopen(fd, "w") as fh:
        fh.write(content)
    return path


# ══════════════════════════════════════════════════════ IPTABLES PARSER ══

def test_iptables_parse_secure():
    path = _write(IPTABLES_SECURE)
    try:
        data, err = parse_iptables(path)
        assert err is None
        filt = data["tables"]["filter"]
        assert filt["policy"]["INPUT"] == "DROP"
        assert len(filt["rules"]) > 0
    finally:
        os.unlink(path)


def test_iptables_parse_risky():
    path = _write(IPTABLES_RISKY)
    try:
        data, err = parse_iptables(path)
        assert err is None
        filt = data["tables"]["filter"]
        assert filt["policy"]["INPUT"] == "ACCEPT"
        assert filt["policy"]["FORWARD"] == "ACCEPT"
    finally:
        os.unlink(path)


def test_iptables_parse_ipv6_detected():
    path = _write(IPTABLES_IPV6)
    try:
        data, err = parse_iptables(path)
        assert err is None
        assert data["is_ipv6"] is True
    finally:
        os.unlink(path)


def test_iptables_parse_missing_file():
    data, err = parse_iptables("/does/not/exist.txt")
    assert err is not None
    assert data == {}


def test_iptables_parse_invalid_format():
    path = _write("<xml>not iptables</xml>", ".xml")
    try:
        data, err = parse_iptables(path)
        assert err is not None
    finally:
        os.unlink(path)


# ══════════════════════════════════════════════════ IPTABLES CHECKS ══

def _risky_data():
    path = _write(IPTABLES_RISKY)
    data, _ = parse_iptables(path)
    os.unlink(path)
    return data


def _secure_data():
    path = _write(IPTABLES_SECURE)
    data, _ = parse_iptables(path)
    os.unlink(path)
    return data


def test_default_policy_flagged():
    findings = check_default_policy_iptables(_risky_data())
    msgs = [f["message"] for f in findings]
    assert any("INPUT" in m and "ACCEPT" in m for m in msgs)
    assert any("FORWARD" in m and "ACCEPT" in m for m in msgs)
    assert all(f["severity"] == "HIGH" for f in findings)


def test_default_policy_clean():
    findings = check_default_policy_iptables(_secure_data())
    assert findings == []


def test_any_any_accept_flagged():
    findings = check_any_any_accept_iptables(_risky_data())
    assert any(f["severity"] == "HIGH" for f in findings)


def test_any_any_accept_clean():
    findings = check_any_any_accept_iptables(_secure_data())
    assert findings == []


def test_internet_ingress_ssh():
    findings = check_internet_ingress_iptables(_risky_data())
    assert any("SSH" in f["message"] for f in findings)


def test_internet_ingress_rdp():
    findings = check_internet_ingress_iptables(_risky_data())
    assert any("RDP" in f["message"] for f in findings)


def test_internet_ingress_clean():
    # Secure ruleset restricts SSH to 10.0.0.0/8 — should not flag SSH
    findings = check_internet_ingress_iptables(_secure_data())
    assert not any("SSH" in f["message"] for f in findings)


def test_forward_chain_flagged():
    findings = check_forward_chain_iptables(_risky_data())
    assert len(findings) >= 1
    assert all(f["severity"] == "MEDIUM" for f in findings)


def test_forward_chain_clean():
    findings = check_forward_chain_iptables(_secure_data())
    assert findings == []


def test_missing_logging_flagged():
    findings = check_missing_logging_iptables(_risky_data())
    assert len(findings) == 1
    assert findings[0]["severity"] == "MEDIUM"


def test_missing_logging_clean():
    findings = check_missing_logging_iptables(_secure_data())
    assert findings == []


def test_icmp_unrestricted_flagged():
    findings = check_icmp_unrestricted_iptables(_risky_data())
    assert len(findings) >= 1
    assert all(f["severity"] == "MEDIUM" for f in findings)


# ══════════════════════════════════════════════════════ AUDIT IPTABLES ══

def test_audit_iptables_risky():
    path = _write(IPTABLES_RISKY)
    try:
        findings, data = audit_iptables(path)
        assert len(findings) > 0
        assert any(f["severity"] == "HIGH" for f in findings)
        assert data  # non-empty dict
    finally:
        os.unlink(path)


def test_audit_iptables_secure():
    path = _write(IPTABLES_SECURE)
    try:
        findings, data = audit_iptables(path)
        high = [f for f in findings if f["severity"] == "HIGH"]
        assert len(high) == 0
    finally:
        os.unlink(path)


def test_audit_iptables_parse_error():
    findings, data = audit_iptables("/nonexistent/file.txt")
    assert len(findings) == 1
    assert data == {}


# ══════════════════════════════════════════════════ NFTABLES PARSER ══

def test_nftables_parse_secure():
    path = _write(NFTABLES_SECURE)
    try:
        tables, err = parse_nftables(path)
        assert err is None
        assert len(tables) >= 1
        chains = tables[0]["chains"]
        assert "input" in chains
        assert chains["input"]["policy"] == "drop"
    finally:
        os.unlink(path)


def test_nftables_parse_risky():
    path = _write(NFTABLES_RISKY)
    try:
        tables, err = parse_nftables(path)
        assert err is None
        chains = tables[0]["chains"]
        assert chains["input"]["policy"] == "accept"
    finally:
        os.unlink(path)


def test_nftables_parse_missing_file():
    tables, err = parse_nftables("/does/not/exist.txt")
    assert err is not None
    assert tables == []


def test_nftables_parse_invalid():
    path = _write("*filter\n:INPUT DROP\n-A INPUT -j ACCEPT\n")
    try:
        tables, err = parse_nftables(path)
        assert err is not None
    finally:
        os.unlink(path)


# ══════════════════════════════════════════════════ NFTABLES CHECKS ══

def _nft_risky():
    path = _write(NFTABLES_RISKY)
    tables, _ = parse_nftables(path)
    os.unlink(path)
    return tables


def _nft_secure():
    path = _write(NFTABLES_SECURE)
    tables, _ = parse_nftables(path)
    os.unlink(path)
    return tables


def test_nft_default_policy_flagged():
    findings = check_default_policy_nftables(_nft_risky())
    assert any("input" in f["message"] for f in findings)
    assert any("forward" in f["message"] for f in findings)
    assert all(f["severity"] == "HIGH" for f in findings)


def test_nft_default_policy_clean():
    findings = check_default_policy_nftables(_nft_secure())
    assert findings == []


def test_nft_any_any_accept_flagged():
    findings = check_any_any_accept_nftables(_nft_risky())
    assert len(findings) >= 1
    assert all(f["severity"] == "HIGH" for f in findings)


def test_nft_any_any_accept_clean():
    findings = check_any_any_accept_nftables(_nft_secure())
    assert findings == []


def test_nft_missing_logging_flagged():
    findings = check_missing_logging_nftables(_nft_risky())
    assert len(findings) >= 1
    assert all(f["severity"] == "MEDIUM" for f in findings)


def test_nft_missing_logging_clean():
    findings = check_missing_logging_nftables(_nft_secure())
    assert findings == []


def test_nft_icmp_unrestricted_flagged():
    findings = check_icmp_unrestricted_nftables(_nft_risky())
    assert len(findings) >= 1


def test_nft_internet_ingress():
    content = """\
table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        tcp dport 22 accept
    }
}
"""
    path = _write(content)
    try:
        tables, _ = parse_nftables(path)
        findings = check_internet_ingress_nftables(tables)
        assert any("SSH" in f["message"] for f in findings)
    finally:
        os.unlink(path)


# ══════════════════════════════════════════════════ AUDIT NFTABLES ══

def test_audit_nftables_risky():
    path = _write(NFTABLES_RISKY)
    try:
        findings, tables = audit_nftables(path)
        assert len(findings) > 0
        assert any(f["severity"] == "HIGH" for f in findings)
        assert tables
    finally:
        os.unlink(path)


def test_audit_nftables_secure():
    path = _write(NFTABLES_SECURE)
    try:
        findings, tables = audit_nftables(path)
        high = [f for f in findings if f["severity"] == "HIGH"]
        assert len(high) == 0
    finally:
        os.unlink(path)


def test_audit_nftables_parse_error():
    findings, tables = audit_nftables("/nonexistent/file.txt")
    assert len(findings) == 1
    assert tables == []


# ── Standalone runner ─────────────────────────────────────────────────────────

if __name__ == "__main__":
    import traceback

    tests = [
        test_iptables_parse_secure, test_iptables_parse_risky,
        test_iptables_parse_ipv6_detected, test_iptables_parse_missing_file,
        test_iptables_parse_invalid_format,
        test_default_policy_flagged, test_default_policy_clean,
        test_any_any_accept_flagged, test_any_any_accept_clean,
        test_internet_ingress_ssh, test_internet_ingress_rdp, test_internet_ingress_clean,
        test_forward_chain_flagged, test_forward_chain_clean,
        test_missing_logging_flagged, test_missing_logging_clean,
        test_icmp_unrestricted_flagged,
        test_audit_iptables_risky, test_audit_iptables_secure, test_audit_iptables_parse_error,
        test_nftables_parse_secure, test_nftables_parse_risky,
        test_nftables_parse_missing_file, test_nftables_parse_invalid,
        test_nft_default_policy_flagged, test_nft_default_policy_clean,
        test_nft_any_any_accept_flagged, test_nft_any_any_accept_clean,
        test_nft_missing_logging_flagged, test_nft_missing_logging_clean,
        test_nft_icmp_unrestricted_flagged, test_nft_internet_ingress,
        test_audit_nftables_risky, test_audit_nftables_secure, test_audit_nftables_parse_error,
    ]

    passed = failed = 0
    for t in tests:
        try:
            t()
            print(f"  PASS  {t.__name__}")
            passed += 1
        except Exception:
            print(f"  FAIL  {t.__name__}")
            traceback.print_exc()
            failed += 1

    print(f"\n{passed} passed, {failed} failed out of {len(tests)} tests.")
    sys.exit(0 if failed == 0 else 1)
